### ISSUE TITLE
Issue in Running Fuzzing

### ISSUE THREAD

**Issue by asa7007** [AIasd/ADFuzz#19]
python ga_fuzzing.py -p 2015 --n_gen 2 --pop_size 2 -r 'town07_front_0' -c 'go_straight_town07' --algorithm_name nsga2-un --has_run_num 4 --objective_weights -1 1 1 0 0 0 0 0 0 0 --check_unique_coeff 0 0.1 0.5 --record_every_n_step 5 --debug 0
  

while running the above command, getting the error as shown below:
 raceback (most recent call last):
  File "/home/adas/anaconda3/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 381, in from_name
    return next(cls.discover(name=name))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ga_fuzzing.py", line 33, in <module>
    if version('carla') != '0.9.9':
  File "/home/adas/anaconda3/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 832, in version
    return distribution(distribution_name).version
  File "/home/adas/anaconda3/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 805, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/adas/anaconda3/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 383, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for carla

Any solution for the same

**Comment by AIasd** [comment]
What version of CARLA do you use?

**Comment by asa7007** [comment]
My Carla version is 0.9.9

I haven't installed Carla manually, just following the steps/commands given
in your repository.

Thanks and Regards
Arpit

**Comment by AIasd** [comment]
can you run `pip freeze` and check the carla version there? Also can you add a line `print(version('carla') )` before the line `if version('carla') != '0.9.9':` to check what carla version is used in the python script?

**Comment by asa7007** [comment]
In pip freeze, I am unable to find Carla. And in the ga_fuzzing.py, when i try to run that file, getting the following error.

Traceback (most recent call last):
  File "ga_fuzzing.py", line 32, in <module>
    print(version('carla') )
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 841, in version
    return distribution(distribution_name).version
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 814, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 429, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for carla

**Comment by AIasd** [comment]
Your issue is probably either with installing a wrong version of carla or a wrong version of carla python api.

First, check if the carla you downloaded indeed is of version 0.9.9.4.

Second, uninstall carla python api `pip uninstall carla`,
then, in `~/Documents/self-driving-cars/carla_0994_no_rss/PythonAPI/carla/dist` (your path might be different), reinstall carla python api:
`easy_install carla-0.9.11-py3.7-linux-x86_64.egg`

**Comment by asa7007** [comment]
Was able to resolve this error.

But now I'm getting the below error

Module tensorflow has no attribute contrib

**Comment by AIasd** [comment]
Can you show the full trace of the error?

**Comment by asa7007** [comment]
ga_fuzzing.py -p 2015 --n_gen 2 --pop_size 2 -r 'town07_front_0' -c 'go_straight_town07' --algorithm_name nsga2-un --has_run_num 4 --objective_weights -1 1 1 0 0 0 0 0 0 0 --check_unique_coeff 0 0.1 0.5 --record_every_n_step 5 --debug 0



2022-12-17 01:37:49.571684: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-17 01:37:50.165704: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-17 01:37:50.165785: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-17 01:37:50.165795: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "ga_fuzzing.py", line 1377, in <module>
    from carla_specific_utils.carla_specific import run_carla_simulation, initialize_carla_specific, correct_spawn_locations_all, get_unique_bugs, choose_weight_inds, determine_y_upon_weights, get_all_y
  File "carla_lbc/carla_specific_utils/carla_specific.py", line 31, in <module>
    from leaderboard.fuzzing import LeaderboardEvaluator
  File "carla_lbc/leaderboard/leaderboard/fuzzing.py", line 47, in <module>
    from srunner.scenarios.control_loss import *
  File "carla_lbc/scenario_runner/srunner/scenarios/control_loss.py", line 20, in <module>
    from srunner.scenariomanager.scenarioatomics.atomic_behaviors import ChangeNoiseParameters, ActorTransformSetter
  File "carla_lbc/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py", line 31, in <module>
    from agents.navigation.basic_agent import BasicAgent, LocalPlanner
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/agents/__init__.py", line 22, in <module>
    from . import scripts
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/agents/scripts/__init__.py", line 21, in <module>
    from . import train
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/agents/scripts/train.py", line 33, in <module>
    from agents.scripts import configs
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/agents/scripts/configs.py", line 26, in <module>
    from agents.scripts import networks
  File "/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/agents/scripts/networks.py", line 30, in <module>
    tfd = tf.contrib.distributions
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by asa7007** [comment]
easy_install carla-0.9.9-py3.7-linux-x86_64.egg

After running easy_install, this is the error that im getting


WARNING: The easy_install command is deprecated and will be removed in a future version.
Processing carla-0.9.9-py3.7-linux-x86_64.egg
removing '/home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/carla-0.9.9-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/carla-0.9.9-py3.7-linux-x86_64.egg
Extracting carla-0.9.9-py3.7-linux-x86_64.egg to /home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages
carla 0.9.9 is already the active version in easy-install.pth

Installed /home/adas/.pyenv/versions/3.8.5/lib/python3.8/site-packages/carla-0.9.9-py3.7-linux-x86_64.egg
Processing dependencies for carla==0.9.9
Searching for carla==0.9.9
Reading https://pypi.org/simple/carla/
No local packages or working download links found for carla==0.9.9
error: Could not find suitable distribution for Requirement.parse('carla==0.9.9')

**Comment by AIasd** [comment]
That easy install error seems ok as long as when you rerun pip freeze, the carla version is changed to 0.9.9

**Comment by AIasd** [comment]
tensorflow error might be related to your tensorflow version. What is it when you run pip freeze?
